custom: ${file(./parameters.yml)}

useDotenv: true

service: ${self:custom.service}

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-deployment-bucket

package:
  excludeDevDependencies: true

frameworkVersion: "3.30.1"

provider:
  name: aws
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  stackName: ${self:service}-${self:provider.stage}
  apiName: ${self:service}-${self:provider.stage}
  runtime: nodejs18.x
  memorySize: 3000
  vpc: ${self:custom.vpc}
  iam:
    role:
      managedPolicies:
        - ${self:custom.managedPolicies}
  tags: ${self:custom.tags}

functions:
  index:
    handler: lambda.handler
    name: ${self:service}-${self:provider.stage}
    
    # Function URL Config
    url: true
    
    # API Gateway Config
    events:
      - httpApi: '*'
